### ISSUE TITLE
Setting defaults before decorator's code runs

### ISSUE THREAD

**Issue by ribizli** [Mitranim/ng-decorate#4]
ES6 imports run before any other code. How to set the default module for those imported components?

**Comment by ribizli** [comment]
I've found a solution what works: set the defaults in a module, not in the main file.

``` js
import defaults from './defaults';

import AppComponent from './AppComponent';
```

**Comment by mitranim** [comment]
Yeah I'm afraid there's no other way. I usually have a tiny module that does some basic configuration, and a larger "main" module that imports all components.
