### ISSUE TITLE
autoinject not working with babel (stage=0)

### ISSUE THREAD

**Issue by ribizli** [Mitranim/ng-decorate#5]
Hi,

this is rather an info (don't know if it can be fixed): `autoinject` creates the attribute on the `__proto__`, but babel somehow overrides it with `undefined` when constructing.

**Comment by mitranim** [comment]
I don't have an angular+babel setup at hand to verify. Does your babel configuration use `__proto__`? It used to be the default class transpilation mode until some recent version. An unfortunate choice, considering that `__proto__` is part of ES6, unsupported in IE. Try updating babel or enabling `spec.protoToAssign` and see if this makes a difference.

**Comment by ribizli** [comment]
Not, I ment your code puts the dependencies on the prototype, but babel defines the class properties in the object (as undefined) directly. So the prototype properties are covered... 
I'm not a babel expert, I'm just guessing this  from the debugger.

**Comment by mitranim** [comment]
Are you talking about class property initialisers? The injected property will be overridden if the initialiser assigns a value. You need to use it without a default value, like so:

``` javascript
@Ambient
class X {
  @autoinject $http;
}
```

**Comment by ribizli** [comment]
It happens in this case.

**Comment by mitranim** [comment]
You're right; I just checked the property initialiser output from the current version of babel, and it always defines own properties, overriding prototype properties. Will try to find ways to circumvent this.

**Comment by j-walker23** [comment]
Damn, wish i would have found this earlier lol.

@Mitranim First, thanks for this lib, it is very cool. 

Do you have any suggestions for a work around with this? Guessing this is why all my deps are undefined. 

I am using typescript with jspm/system along with the plugin-typescript loader. Is this babel issue still expected?

**Comment by j-walker23** [comment]
Nevermind, it seems to work with some decorators. 
With classes decorated with `Ambient` the autoinjects are undefined. Probably some confusion on my part.

**Comment by mitranim** [comment]
There's probably still an issue with Babel. If you're using TypeScript, it's more likely that you're getting undefined for injected values by trying to access them before the application is bootstrapped. They're assigned during the run phase.

**Comment by j-walker23** [comment]
Yep, just confusion with how to use angular and es6 modules together. 

Thanks for you help!
